"""baseline schema

Revision ID: cde15cf6bb6e
Revises: 
Create Date: 2026-07-19 22:36:26.892309
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cde15cf6bb6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Pre-Alembic databases already own their schema. The next revision does
    # the compatible column-level upgrade; this baseline is only recorded.
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("conversations") or inspector.has_table("agent_runs"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('answer_hash', sa.String(length=64), nullable=False),
    sa.Column('answer_salt', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_challenges_expires_at'), ['expires_at'], unique=False)

    op.create_table('model_configs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='模型配置ID'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='模型供应商，例如 glm / qwen / minimax / nvidia'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='前端展示名称'),
    sa.Column('model_id', sa.String(length=100), nullable=False, comment='实际请求模型ID'),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='OpenAI-compatible base_url'),
    sa.Column('api_key_env', sa.String(length=100), nullable=False, comment='API Key 对应的环境变量名'),
    sa.Column('api_shape', sa.String(length=50), nullable=False, comment='API 形态：chat_completions / responses / image'),
    sa.Column('support_streaming', sa.Boolean(), nullable=False, comment='是否支持流式输出'),
    sa.Column('support_tools', sa.Boolean(), nullable=False, comment='是否支持工具调用'),
    sa.Column('support_image', sa.Boolean(), nullable=False, comment='是否支持图片生成'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('extra_body_json', sa.Text(), nullable=True, comment='第三方模型额外参数，JSON字符串'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('traceback_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_exceptions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_exceptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_exceptions_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_exceptions_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_exceptions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_exceptions_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('username_key', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username_key'), ['username_key'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='会话ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('agent_mode', sa.String(length=50), nullable=False, comment='当前会话默认 Agent 模式'),
    sa.Column('default_model', sa.String(length=100), nullable=True, comment='当前会话默认模型'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='所属用户ID；旧数据迁移期间允许为空'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='消息ID'),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='所属会话ID'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='消息角色：user / assistant / tool / system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='生成该消息使用的模型'),
    sa.Column('agent_name', sa.String(length=100), nullable=True, comment='生成该消息的 Agent 名称'),
    sa.Column('sequence_no', sa.Integer(), nullable=False, comment='消息顺序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('sdk_item_json', sa.Text(), nullable=True, comment='OpenAI Agents SDK Session 原始 item JSON'),
    sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False, comment='是否在聊天消息列表中展示；工具和推理 item 仅用于记忆'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Agent运行ID'),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='所属会话ID'),
    sa.Column('user_message_id', sa.String(length=36), nullable=True, comment='本次运行对应的用户消息ID'),
    sa.Column('model_config_id', sa.String(length=36), nullable=True, comment='模型配置ID'),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='Agent名称'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='实际模型ID'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='运行状态：running / completed / failed'),
    sa.Column('input_text', sa.Text(), nullable=False, comment='用户输入'),
    sa.Column('final_output', sa.Text(), nullable=True, comment='最终输出'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='运行耗时毫秒'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('model_compares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('model_config_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('winner_model_config_id', sa.String(length=36), nullable=True),
    sa.Column('judge_report_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_compares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_compares_run_id'), ['run_id'], unique=True)

    op.create_table('run_events',
    sa.Column('id', sa.String(length=36), nullable=False, comment='事件ID'),
    sa.Column('run_id', sa.String(length=36), nullable=False, comment='所属AgentRun ID'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='事件在本次运行中的顺序'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='标准化事件类型'),
    sa.Column('event_name', sa.String(length=100), nullable=True, comment='SDK原始事件名称'),
    sa.Column('payload_json', sa.Text(), nullable=False, comment='事件数据JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='事件创建时间'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_events_run_id_seq')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('token_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('model_config_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('usage_type', sa.String(length=30), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_model_config_id'), ['model_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_run_id'), ['run_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False, comment='工具调用记录ID'),
    sa.Column('run_id', sa.String(length=36), nullable=False, comment='所属AgentRun ID'),
    sa.Column('sdk_tool_call_id', sa.String(length=100), nullable=True, comment='SDK原始工具调用ID'),
    sa.Column('seq', sa.Integer(), nullable=True, comment='本次运行中的事件顺序'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('arguments_json', sa.Text(), nullable=True, comment='工具参数JSON'),
    sa.Column('output', sa.Text(), nullable=True, comment='工具输出'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='running / success / error'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='工具调用耗时'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_sdk_tool_call_id'), ['sdk_tool_call_id'], unique=False)

    op.create_table('model_compare_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compare_id', sa.String(length=36), nullable=False),
    sa.Column('model_config_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('scores_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compare_id'], ['model_compares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compare_id', 'model_config_id', name='uq_model_compare_result_model')
    )
    with op.batch_alter_table('model_compare_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_compare_results_compare_id'), ['compare_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_compare_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_compare_results_compare_id'))

    op.drop_table('model_compare_results')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_sdk_tool_call_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_run_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_run_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_model_config_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_model'))
        batch_op.drop_index(batch_op.f('ix_token_usage_created_at'))

    op.drop_table('token_usage')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_events_event_type'))

    op.drop_table('run_events')
    with op.batch_alter_table('model_compares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_compares_run_id'))

    op.drop_table('model_compares')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_conversation_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username_key'))

    op.drop_table('users')
    with op.batch_alter_table('system_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_exceptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_system_exceptions_run_id'))
        batch_op.drop_index(batch_op.f('ix_system_exceptions_path'))
        batch_op.drop_index(batch_op.f('ix_system_exceptions_level'))
        batch_op.drop_index(batch_op.f('ix_system_exceptions_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_exceptions_category'))

    op.drop_table('system_exceptions')
    op.drop_table('model_configs')
    with op.batch_alter_table('login_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_challenges_expires_at'))

    op.drop_table('login_challenges')
    # ### end Alembic commands ###
